export interface jobData {
    fullName: String,
    email: String,
    bookingDate: string,
    address: String,
    phone: String,
    totalPrice: String,
    products: Array<[]>,
    stripeData: Array<[]>,
    paidStatus: Boolean,
    jobStatus: String,
    bedrooms: String,
    bathrooms: String,
    balcony: String,
    separateToilet: String,
    studyRoom: String,
    wallWash: String,
    fridge: String,
    garage: String,
    blinds: String,
    steamLiving: String,
    steamBedroom: String,
    steamHallway: String,
    steamStairs: String,
    service: String
}